export { default as Authentication } from "./authentication";
export { default as Dashboard } from "./dashborad";
export { default as Assets } from "./assetsPage";
export { default as MainMapView } from "./mainMapView";
export { default as Notifications } from "./notifications";
export { default as Profile } from "./profile"
export { default as Messages } from "./messages"
export { default as OutOfZone } from "./outOfZone"
export { default as TotalTrip } from "./totalTrip"
export { default as Expired } from "./expired"
export { default as EditProfile } from "./editProfile"
export { default as Feedback } from "./feedback"
export { default as Settings } from "./settings"
export { default as Support } from "./support"
export { default as TrackOnMap } from "./trackOnMap"
export { default as ShareLocation } from "./shareLocation"
export { default as CommandScreen } from "./commandScr"
export { default as DeviceDetail } from "./deviceDetail"
export { default as Reports } from "./reports"
export { default as DownloadReports } from "./downloadReport"
export { default as PDFViewComp } from "./pdfView"
export { default as HistoryReplay } from "./historyReplay"
export { default as TripReplay } from "./tripReplay"
export { default as FuelDetail } from "./fuelDetails"